### ISSUE TITLE
Cannot write more than one Profile to MySQL database. 

### ISSUE THREAD

**Issue by se-linde** [newmanix/itc260-sp15-gig-central#112]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?: BUG. 

###_Severity (1-4; 1 - not severe, 4 - very severe):
2 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 
Cannot write more than one Profile to MySQL database. Consequently, you cannot list more than the first profile made under View Profiles. When you make a profile under Add Profiles, it'll then appear under the View profiles page. However, it only shows the first profile that you made. Any subsequent profiles show that they're accepted, but don't show up. 

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
It would either write more than one profile to the SQL DB, and then make them viewable, or the website would recognize that you already have one profile in the DB, and will prevent you from making another one. This is a dev scope that has to be decided by the Dev Team. 

###_Actual Behavior - what the behavior is instead, for bugs only: 
You only see the very first profile made. Screenshot attached. This is because it only writes that first profile to the SQL database. 

###_Steps to Repro the Issue, for bugs only:
* Step 1: Go to Profiles/Add a Profile on the Nav bar.
* Step 2: Fill out all of the fields, including uploading an image. Make it obvious test data by putting in some variant of 'test' in every field. 
* Step 3: For the email field, please use either your own email, or example.com. We don't want to put in a stranger's email address. 
* Step 4: Click the Add button. 

###_Other Notes, for bug/task/future request: 
![screen shot 2017-05-21 at 8 54 19 pm](https://cloud.githubusercontent.com/assets/17558449/26292088/1f9c4132-3e68-11e7-9f87-d9eefdec84bc.png)
![screen shot 2017-05-21 at 9 00 31 pm](https://cloud.githubusercontent.com/assets/17558449/26292184/9ceac474-3e68-11e7-81da-e8d4e71bcdeb.png)

**Comment by dwaynelinde** [comment]
I am closing this issue; I have verified that I can add more than one profile now to the Profile Page. 

It also writes those profiles to the DB. 
![screen shot 2017-05-31 at 12 15 25 am](https://cloud.githubusercontent.com/assets/17558449/26620118/4b65648a-4596-11e7-90f9-c3ede1f8ac90.png)


![screen shot 2017-05-31 at 12 14 20 am](https://cloud.githubusercontent.com/assets/17558449/26620093/33334f58-4596-11e7-8fb2-2e3583a9efd0.png)
