### ISSUE TITLE
Disclaimer/pages

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#22]
simple? and unused

**Comment by mitchthompson** [comment]
Disclaimer controller is very basic. Just loads disclaimer view which is just the text you see on the disclaimer page plus the theme. The Pages controller is not used anywhere in the app. Has one function. 

Report: https://docs.google.com/document/d/12zNmhKele-YqZDsmjCdKP1UBCRSUM2V4lqu9-NGE2Lw/edit?usp=sharing
