### ISSUE TITLE
fix contact us subject options

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#30]
This is what is being display in the dropdown menu:
<img width="400" alt="screen shot 2016-05-15 at 11 21 27 am" src="https://cloud.githubusercontent.com/assets/13126219/15275977/3d046720-1a8f-11e6-825a-8cfe6fb8be32.png">

**change it for:** 
<img width="189" alt="screen shot 2016-05-15 at 11 40 33 am" src="https://cloud.githubusercontent.com/assets/13126219/15276076/f0354dbc-1a91-11e6-8358-5b9c286f0ea1.png">

**Comment by jameriah30** [comment]
I fixed the contact subject drop down menu to display the appropriate subjects.
