### ISSUE TITLE
"Lets get started" button needs to be deleted - FAQ

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#31]
If we are not using that button we need to delete it from the FAQ section

<img width="1440" alt="screen shot 2016-05-15 at 11 22 37 am" src="https://cloud.githubusercontent.com/assets/13126219/15275982/6239c3f0-1a8f-11e6-9713-6ef891fcf2f3.png">

**Comment by stephine** [comment]
Deleted "Let's get started" button
