### ISSUE TITLE
indent title contact form

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#33]
indent to the left title 

<img width="495" alt="screen shot 2016-05-15 at 11 25 57 am" src="https://cloud.githubusercontent.com/assets/13126219/15276002/f21c0c4e-1a8f-11e6-929e-9cfebda1b4e8.png">

**Comment by jameriah30** [comment]
Contact for heading "Company Information" is now centered with the contact form.

**Comment by jameriah30** [comment]
*form heading
