### ISSUE TITLE
fix logo contact page

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#35]
the logo is not being displayed on the contact page

<img width="590" alt="screen shot 2016-05-15 at 11 28 46 am" src="https://cloud.githubusercontent.com/assets/13126219/15276007/42973ee6-1a90-11e6-87c1-4a85e456181b.png">

**Comment by Hastwell** [comment]
Issue resolved with 3a010165ef9c4bf5489fa0fd5ecb5095c08f7883
