### ISSUE TITLE
get rid off "Here are FAQs" h2

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#37]
We have it as a title and then as an H2 (repetitive)

<img width="900" alt="screen shot 2016-05-15 at 11 32 37 am" src="https://cloud.githubusercontent.com/assets/13126219/15276030/dd125ce4-1a90-11e6-9278-f4210bbecb8d.png">

**Comment by jameriah30** [comment]
Just deleted, will commit change
