### ISSUE TITLE
re-direct "View More" button map

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#50]
We need to make that link to go somewhere? list of venues for example.

<img width="528" alt="screen shot 2016-05-17 at 4 51 32 pm" src="https://cloud.githubusercontent.com/assets/13126219/15343207/cac2859e-1c4f-11e6-8029-c3a334fa4c82.png">

**Comment by jameriah30** [comment]
The "View more" button now redirects to venues list.
