### ISSUE TITLE
Change order dropdown menu "Profiles"

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#52]
move up "View Profiles" first and below that "Add Profiles"

<img width="451" alt="screen shot 2016-05-17 at 4 54 09 pm" src="https://cloud.githubusercontent.com/assets/13126219/15343251/18b36d04-1c50-11e6-8250-2a1f79e23626.png">

**Comment by jameriah30** [comment]
I changed the order of the "Profiles" drop down menu so that "View Profiles" is before "Add Profiles"
