### ISSUE TITLE
Post button align to right on "Post Gigs"

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#60]
The button its floating on the left. We need to align it to the right, below the text box.

<img width="1031" alt="screen shot 2016-05-19 at 4 13 58 pm" src="https://cloud.githubusercontent.com/assets/13126219/15413436/0b61c92a-1de5-11e6-9043-3e881e2c7057.png">

**Comment by mitchthompson** [comment]
Button aligned right now.
