### ISSUE TITLE
Fix "Add profile" page on Mozilla

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#64]
It prompts a 404 error on Mozilla firefox

<img width="1440" alt="screen shot 2016-05-24 at 1 09 52 pm" src="https://cloud.githubusercontent.com/assets/13126219/15518269/e51cc4c0-21b0-11e6-9f27-8a375cb9ccfd.png">

**Comment by virgofreedom** [comment]
Please download it and copy into img/ folder outside the application folder
[this is image of picID](http://rattananeak.com/itc260/gig-central/img/picID.jpg)
