### ISSUE TITLE
Clean up and consolidate Sql statements for Add Profile

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#66]
We have two sql files. One seems to have the statements for the Add Profile feature (my_gig_central_update_rattana.sql) but also has unrelated statements. it needs to be clean up and add to the gigCentral-tablesAndData.sql

There is a data error because that missing data:

<img width="777" alt="screen shot 2016-05-24 at 1 21 33 pm" src="https://cloud.githubusercontent.com/assets/13126219/15518586/80440836-21b2-11e6-8238-a3dfc7fd5d8b.png">

**Comment by virgofreedom** [comment]
Please update the sql with my sql that I add to the sql folder. Because I created more field inside the Profile table.
