### ISSUE TITLE
Change <title> for profile page

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#71]
It is showing a weird message:

<img width="734" alt="screen shot 2016-05-24 at 1 43 03 pm" src="https://cloud.githubusercontent.com/assets/13126219/15519283/90c391a6-21b5-11e6-9294-1fc9f09f7040.png">

Change it for **< title >Add Profile< /title >**

<img width="762" alt="screen shot 2016-05-24 at 1 43 30 pm" src="https://cloud.githubusercontent.com/assets/13126219/15519293/9bc90ff4-21b5-11e6-82e6-1b6c4e521204.png">

**Comment by Hastwell** [comment]
No $data is being passed to view pages; messed-up title is due to bootstrap theme requiring the non-existent $data['title']

**Comment by virgofreedom** [comment]
Fixed...I already added the $data['title']. Will update into git soon.
