### ISSUE TITLE
Fix "Submit Message" button styling

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#72]
Add some space between the text box and the **"Submit Message" button** on the Contact Us page, like this:

<img width="638" alt="screen shot 2016-05-24 at 1 46 50 pm" src="https://cloud.githubusercontent.com/assets/13126219/15519384/164d11da-21b6-11e6-86f2-3550bbff6851.png">

**Also add this styling to line 312 on the CSS file:**

This is were the styling is, just make sure it does not affect something else on the page. It seems to be global:
**input,
button,
select,
textarea {**
It will fix the style for the contact form

background-color: #ffffff;
background-image: none;
border: 1px solid #dce4ec;
border-radius: 4px;
-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
-webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;

**Comment by Hastwell** [comment]
These style changes will also affect:
- Profile view page add.php
- Gigs view page add.php
- Admin view pages admin.php, add.php, login.php
- Venues view page add.php
- Passphrase view component index.php (application/views/passphrase/)

**Comment by luisgamboa** [comment]
Hey Stephie, just make sure it won't change anything else on the page. It seems is a global styling. Thanks
