### ISSUE TITLE
Fix Gig view / date posted-last update

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#74]
Clicking View details leads to the first gig and not the new one
                New company is created but a new gig is not.

Datestamps not working when new gigs are posted
Says:	Date Posted: 0000-00-00 00:00:00
                Last Update: 0000-00-00 00:00:00

More detail information from report:
[https://docs.google.com/document/d/1lPsBG-tfyiIAs41cD8q5s98AH7BzjjiiyUoFa6MdkDA/edit?pref=2&pli=1](url)

Spencer site:
[http://spencerechon.com/itc260/gigcentral/](url)

**Comment by sechon** [comment]
Fixed!
